CREATE TABLE PERSONA (
    idpersona INT IDENTITY (1,1) NOT NULL,
    primernombre VARCHAR(20) NOT NULL,
	segundonombre VARCHAR(20),
    apellidopaterno VARCHAR(20),
	apellidomaterno VARCHAR(20) NOT NULL,
    telefono VARCHAR(20),
    ci VARCHAR(20) NOT NULL,
    correo VARCHAR(20),
    estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (idpersona) 
);

CREATE TABLE USUARIO (
    idusuario INT IDENTITY (1,1) NOT NULL,
    idpersona INT NOT NULL,
    nombreuser VARCHAR(20) NOT NULL,
    contraseña VARCHAR(100) NOT NULL,
    fechareg DATETIME NOT NULL,
	PRIMARY KEY (idusuario)
);

CREATE TABLE ROL (
    idrol INT IDENTITY (1,1) NOT NULL,
    nombre VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (idrol)
);

CREATE TABLE USUARIO_ROL (
    idusuario_rol INT IDENTITY (1,1) NOT NULL,
    idusuario INT NOT NULL,
    idrol INT NOT NULL,
    fechaasigna DATETIME NOT NULL,
    estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (idusuario_rol)
);

CREATE TABLE CLIENTE (
    idcliente INT IDENTITY (1,1) NOT NULL,
    idpersona INT NOT NULL,
    tipocliente VARCHAR(20) NOT NULL,
    codigocliente VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (idcliente)
);

CREATE TABLE VENTA (
    idventa INT IDENTITY (1,1) NOT NULL,
    idcliente INT NOT NULL,
    idvendedor INT NOT NULL,
    fecha DATETIME NOT NULL,
    total DECIMAL NOT NULL,
    estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (idventa)
);

CREATE TABLE DETALLE_VENTA (
    iddetalle_venta INT IDENTITY (1,1) NOT NULL,
    idventa INT NOT NULL,
    idproducto INT NOT NULL,
    cantidad INT NOT NULL,
    precioventa DECIMAL NOT NULL,
    subtotal DECIMAL NOT NULL,
    estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (iddetalle_venta)
);

CREATE TABLE DETALLE_ING (
    iddetalle_ing INT IDENTITY (1,1) NOT NULL,
    idproducto INT NOT NULL,
    idingreso INT NOT NULL,
    fechavenc DATETIME NOT NULL,
    cantidad INT NOT NULL,
    preciocosto DECIMAL NOT NULL,
    precioventa DECIMAL NOT NULL,
    subtotal DECIMAL NOT NULL,
    estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (iddetalle_ing)
);

CREATE TABLE INGRESO (
    idingreso INT IDENTITY (1,1) NOT NULL,
    idproveedor INT NOT NULL,
    fechaingreso DATETIME NOT NULL,
    total DECIMAL NOT NULL,
    estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (idingreso)
);

CREATE TABLE PRODUCTO (
    idproducto INT IDENTITY (1,1) NOT NULL,
    idtipo_producto INT NOT NULL,
    nombre VARCHAR(20) NOT NULL,
    codigobarra VARCHAR(50) NOT NULL,
    idmarca INT NOT NULL,
    unidad VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (idproducto)
);

CREATE TABLE PROVEE (
    idprovee INT IDENTITY (1,1) NOT NULL,
    idproducto INT NOT NULL,
    idproveedor INT NOT NULL,
    fecha DATETIME NOT NULL,
    precio DECIMAL NOT NULL,
	PRIMARY KEY (idprovee)
);

CREATE TABLE PROVEEDOR (
    idproveedor INT IDENTITY (1,1) NOT NULL,
    nombre VARCHAR(30) NOT NULL,
    telefono VARCHAR(15) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (idproveedor)
);

CREATE TABLE TIPO_PRODUCTO (
    idtipo_producto INT IDENTITY (1,1) NOT NULL,
    nombre VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (idtipo_producto)
);

CREATE TABLE MARCA (
    idmarca INT IDENTITY (1,1) NOT NULL,
    nombre VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (idmarca)
);



ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY (idpersona) REFERENCES PERSONA (idpersona);

ALTER TABLE USUARIO_ROL
ADD CONSTRAINT FK_USUARIO_ROL_USUARIO FOREIGN KEY (idusuario) REFERENCES USUARIO (idusuario);

ALTER TABLE USUARIO_ROL
ADD CONSTRAINT FK_USUARIO_ROL_ROL FOREIGN KEY (idrol) REFERENCES ROL (idrol);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_PERSONA FOREIGN KEY (idpersona) REFERENCES PERSONA (idpersona);

ALTER TABLE VENTA
ADD CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (idcliente) REFERENCES CLIENTE (idcliente);

ALTER TABLE DETALLE_VENTA
ADD CONSTRAINT FK_DETALLE_VENTA_VENTA FOREIGN KEY (idventa) REFERENCES VENTA (idventa);

ALTER TABLE DETALLE_VENTA
ADD CONSTRAINT FK_DETALLE_VENTA_PRODUCTO FOREIGN KEY (idproducto) REFERENCES PRODUCTO (idproducto);

ALTER TABLE DETALLE_ING
ADD CONSTRAINT FK_DETALLE_ING_PRODUCTO FOREIGN KEY (idproducto) REFERENCES PRODUCTO (idproducto);

ALTER TABLE DETALLE_ING
ADD CONSTRAINT FK_DETALLE_ING_INGRESO FOREIGN KEY (idingreso) REFERENCES INGRESO (idingreso);

ALTER TABLE INGRESO
ADD CONSTRAINT FK_INGRESO_PROVEEDOR FOREIGN KEY (idproveedor) REFERENCES PROVEEDOR (idproveedor);

ALTER TABLE PROVEE
ADD CONSTRAINT FK_PROVEE_PRODUCTO FOREIGN KEY (idproducto) REFERENCES PRODUCTO (idproducto);

ALTER TABLE PROVEE
ADD CONSTRAINT FK_PROVEE_PROVEEDOR FOREIGN KEY (idproveedor) REFERENCES PROVEEDOR (idproveedor);

ALTER TABLE PRODUCTO
ADD CONSTRAINT FK_PRODUCTO_TIPO_PRODUCTO FOREIGN KEY (idtipo_producto) REFERENCES TIPO_PRODUCTO (idtipo_producto);

ALTER TABLE PRODUCTO
ADD CONSTRAINT FK_PRODUCTO_MARCA FOREIGN KEY (idmarca) REFERENCES MARCA (idmarca);
